### ISSUE TITLE
Allow to override --nocheck-unique-key-changes and --alter-foreign-keys-method=auto

### ISSUE THREAD

**Issue by bellatoris** [adangel/liquibase-percona#29]
I need to set check-unique-key-changes and specify alter-foreign-keys-method as rebuild_constraints.

https://github.com/adangel/liquibase-percona/blob/c8f1089feb0a06430df938b3fc5c02c67ab91fc2/src/main/java/liquibase/ext/percona/PTOnlineSchemaChangeStatement.java#L122-L123

If there are option to disable --nocheck-unique-key-changes and --alter-foreign-keys-method=auto, it is really helpful.

**Comment by adangel** [comment]
This is currently not possible, as these options are always added:

https://github.com/adangel/liquibase-percona/blob/c8f1089feb0a06430df938b3fc5c02c67ab91fc2/src/main/java/liquibase/ext/percona/PTOnlineSchemaChangeStatement.java#L122-L123

But we could add some kind of new option (boolean), so that these are not added by default. You need to specify your own options via `liquibase.percona.options`.

Would you need this configuration per change? (the described above would be a global option)

**Comment by bellatoris** [comment]
> You need to specify your own options via liquibase.percona.options.

It does not help this case. Because the default options are always added later than my own options. So it override my options always.

**Comment by bellatoris** [comment]
> Would you need this configuration per change? (the described above would be a global option)

Of course it would be better if it is possible. Now, however, I just need global option.

**Comment by adangel** [comment]
Hi @bellatoris ,
I've fixed this. Would you mind to test it?
You can now set the property `liquibase.percona.options`. It defaults to be `--alter-foreign-keys-method=auto --nocheck-unique-key-change`, but you can change it to your needs.

Just download the 1.6.0-SNAPSHOT jar from here:
https://oss.sonatype.org/content/repositories/snapshots/com/github/adangel/liquibase/ext/liquibase-percona/1.6.0-SNAPSHOT/liquibase-percona-1.6.0-20190414.195807-2.jar

Or simply use the snapshot dependency, see https://github.com/adangel/liquibase-percona#using-snapshots
