### ISSUE TITLE
Using quotes for liquibase.percona.options doesn't always work

### ISSUE THREAD

**Issue by duronrulez** [adangel/liquibase-percona#37]
Hey,

im not sure im using the liquibase.percona.options properly, but when i try to set options i get weird errors saying that they are not a valid variable name.

Ex (i modified my /usr/bin/liquibase file to support the java system properties) so it tries to run the following command now:

`java -cp ...libs... liquibase.percona.options="--critical-load=\"Threads_running=160\" --alter-foreign-keys-method=\"auto\"" liquibase.integration.commandline.Main --logLevel=info --contexts=test --username=test --password=test --url=jdbc:mysql://localhost/test --driver=com.mysql.jdbc.Driver --classpath=/usr/share/java/mysql.jar:/test/database/ --changeLogFile=databaseChangeLog.xml update`

which results in the following error (edited before and after):
```
........
INFO 7/17/19 8:26 AM: liquibase: databaseChangeLog.xml: ***: Executing: pt-online-schema-change --critical-load="Threads_running=160 --alter-foreign-keys-method="auto --alter="***" --host=localhost --port=3306 --user=test --password=*** --execute D=test,t=test
Usage: pt-online-schema-change [OPTIONS] DSN
Errors in command-line arguments:
   * Invalid --critical-load: "Threads_running is not a variable name
   * Invalid --alter-foreign-keys-method value: "auto
pt-online-schema-change alters a table's structure without blocking reads or
.......
```

Any ideas whats going wrong?

**EDIT:** Managed to get it working using the --config option, good enough for what i need.

**Comment by adangel** [comment]
Great that you got it working via the `--config file.conf` option.
I think, it has something to do with the quotes, as you can see, they ended up in the arguments of pt-osc:

> Invalid --alter-foreign-keys-method value: "auto

I suspect, it has something to do with the method [joinQuotedArguments](https://github.com/adangel/liquibase-percona/blob/0246bab962cd858c824ddb4104a0d1776670d4fe/src/main/java/liquibase/ext/percona/PTOnlineSchemaChangeStatement.java#L80).

In your case, you wouldn't need the extra quotes (since there are no spaces), so it should work if you just use
`-Dliquibase.percona.options="--critical-load=Threads_running=160 --alter-foreign-keys-method=auto"`.

I think, I'll keep this open, since obviously the option/space/quote handling is wrong.

**Comment by duronrulez** [comment]
Thanks for fixing anyway :)
